### ISSUE TITLE
No 2021 branches in .build

### ISSUE THREAD

**Issue by JengaMasterG** [microsoft/surface-duo-oss#1]
Running repo sync on a 2021 kernel revision branch causes the following errors:

`platform/prebuilts/clang/host/linux-x86fatal: couldn't find remote ref refs/heads/surfaceduo/10/2021.115.52
surface-duo-oss-kernel.build:`
`fatal: couldn't find remote ref refs/heads/surfaceduo/10/2021.115.52`

`error: Cannot checkout surface-duo-oss-kernel.build: ManifestInvalidRevisionError: revision surfaceduo/10/2021.115.52 in surface-duo-oss-kernel.build not found`
`error: in sync: revision surfaceduo/10/2021.115.52 in surface-duo-oss-kernel.build not found`

**Comment by charlienilsson** [comment]
Thanks for letting us know about this.  We updated the manifest and related 2021.115.* branches.  Please re-sync to get the changes.
